<?php
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$payment = $block->getMFInformation();
$title   = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($title); ?>
<?php if ($payment): ?>
    <table class="data-table admin__table-secondary">
        <tr>
            <th><?= $block->escapeHtml('Invoice ID'); ?>:</th>
            <td>
                <?php if (isset($payment['invoice']['url'])): ?>
                    <a href="<?= $block->escapeHtml($payment['invoice']['url']); ?>" target="_blank">
                        <?= $block->escapeHtml($payment['invoice']['id']); ?>
                    </a>
                <?php else: ?>
                    <?= $block->escapeHtml($payment['invoice']['id']); ?>
                <?php endif; ?>
            </td>
        </tr>

        <?php foreach ($payment['info'] as $label => $value): ?>
            <tr>
                <th><?= $block->escapeHtml($label); ?>:</th>
                <td>
                    <?= $block->escapeHtml($value); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

<?= $block->getChildHtml() ?>
